### ISSUE TITLE
Querying not working in Rails 6.1

### ISSUE THREAD

**Issue by zokioki** [palkan/pgrel#13]
After upgrading to Rails 6.1, calling `store` will raise a `NoMethodError` for `where_clause_factory`. To reproduce, you can run the following type of query:

```ruby
User.where.store(:some_data_column, foo: 'bar')

#=> NoMethodError: undefined method `where_clause_factory' for #<User::ActiveRecord_Relation:0x00007fe1cdb66230>
```

It looks like `where_clause_factory` was [recently removed](https://github.com/rails/rails/commit/550ce69f8adcd19542453ae03ac837a9ac8adf4b) in favor of `build_where_clause`.
